[package]
name = "ize-repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ize-core = { path = "../ize-core" }
rustyline = "13.0"